WANdisco/wandisco-documentation-ldm

- docs/operation-ui.md
As discussed, this content can be split up depending on how the UI changes will be added in.
> Exclusion templates through the UI

- docs/about.md
Update intro paragraph with  new marketing copy: https://jira.wandisco.com/browse/DOCU-665
I also pruned this page a little and removed an out of date graphic. A new version can be added back in if necessary before release but it's not worth holding up the docs over.
> Shona docu665

- docs/command-reference.md
> update credentials-provider command to optional from mandatory

- docs/operation-ui.md
What the Overwrite/Skip options mean in the UI. This is half the job as CLI updates are still required.
https://jira.wandisco.com/browse/DOCU-628
> Update create migration with skip options in UI instructions

- docs/operation-ui.md
- docs/quickstart.md
https://jira.wandisco.com/browse/DOCU-627
https://jira.wandisco.com/browse/DOCU-666
> Updates to Quickstart and how to upgrade a license

- docs/installation.md
New table for UI directories. Did I match them correctly?!
https://jira.wandisco.com/browse/DOCU-680
> Add UI directories to Installation topic

- docs/configuration.md
I've added the UI configuration section in the same style as the LDM section, and refactored the headings throughout so they account for the new level of hierarchy.
I've matched the default/accepted values style where relevant, in some later cases I'm not sure what the accepted values are or the defaults aren't relevant, so I've left those out.
> DOCU-676 - UI Configuration

- docs/api-reference.md
- docs/configuration.md
- docs/installation.md
https://jira.wandisco.com/browse/DOCU-679
> Cleanup: installation, api ref, and config topics

- docs/command-reference.md
- docs/configuration.md
- docs/operation-cli.md
- docs/operation-ui.md
These are mostly out of date, and the new ones are much longer.
Please don't take this as a decision from me that they **should** be removed. It's merely a suggestion given what it would take to maintain this in my experience.
> DOCU-687 Removing example outputs

- docs/configuration.md
Also an additional improvement to the Server SSL section to make it more inline with other sections.
> HDFS inotify to config section

- docs/operation-cli.md
> add final review edits to cli topic

- docs/command-reference.md
- docs/configuration.md
- docs/installation.md
- docs/operation-cli.md
final fixes for today's release!
> Shona docu705

- docs/command-reference.md
- docs/operation-cli.md
This does not include the UI changes (they are not yet available).
> Exclusion add date command

- docs/operation-ui.md
DOCU-802 to remove mention of trial license (not relevant for GA).
> update upgrade license info to future proof against preview options

- docs/operation-ui.md
As per https://jira.wandisco.com/browse/DOCU-876
Had to quickly redo in this new branch to remove some overlap with develop
> Added HDFS to configurable target storages in operation-ui.md

- docs/troubleshooting.md
- sidebars.js
Based on https://jira.wandisco.com/browse/DOCU-886
Further info in https://jira.wandisco.com/browse/LM2-1678
Highly underconfident in this, but hoping it'll suffice until I can improve the quality of this section.
> Added ADLS2 Ignore Permissions to troubleshooting

- docs/configure-exclusions.md
Based on this ticket https://jira.wandisco.com/browse/DOCU-899
For 1.10, therefore merging in to develop
> Added information about default exclusions

- docs/manage-migrations.md
Simple PR, as per https://jira.wandisco.com/browse/DOCU-920
> Added new migration state

- docs/installation.md
As per https://jira.wandisco.com/browse/DOCU-911
> Removed inaccurate/outdated installation info

- docs/manage-migrations.md
I've confirmed this is ready to go live now.
> Added stop and resume migration tutorial

- docs/command-reference.md
Based off of the following ticket: https://jira.wandisco.com/browse/LM2-1062
> Created initial documentation of S3A upload buffering

- docs/command-reference.md
In reference to this unhelpful ticket (my fault) https://jira.wandisco.com/browse/DOCU-933
Which is in turn in reference to this significantly more helpful ticket (not my fault) https://jira.wandisco.com/browse/LM2-1762
> Updated status command reference for 1.10

- docs/command-reference.md
Based on this ticket https://jira.wandisco.com/browse/DOCU-960
> Added --transfers parameter to status

- docs/manage-migrations.md
https://jira.wandisco.com/browse/DOCU-952
> Removed inaccurate text about being unable to resume stopped migrations

- docs/command-reference.md
https://jira.wandisco.com/browse/DOCU-962
> Added --diagnostics to status command

- docs/command-reference.md
Full completion of this ticket https://jira.wandisco.com/browse/DOCU-962
Additionally added a link to help at the top of the page for user convenience
> Added simple example for --diagnostics on status

- docs/command-reference.md
Small PR, as per https://jira.wandisco.com/browse/DOCU-978
> New S3A Parameters

- docs/command-reference.md
- docs/troubleshooting.md
Based on https://jira.wandisco.com/browse/DOCU-982
> Documented workaround for --rule-names auto-completion in troubleshooting, mentioned in command reference

- docs/configuration-data-migrations.md
As per https://jira.wandisco.com/browse/DOCU-996
> Added note explaining to restart cluster services

- docs/about.md
- docs/api-reference.md
- docs/configuration-metadata.md
- docs/connect-metastores.md
- docs/define-metadata-rules.md
- docs/installation.md
- docs/manage-metadata-migrations.md
- docs/migrate-metadata.md
- docs/prereqs.md
As per https://jira.wandisco.com/browse/DOCU-997
> Removed references to metadata migration as a preview feature

- docs/uninstall.md
As per https://jira.wandisco.com/browse/DOCU-998
> Added Azure HDI packages to uninstallation instructions

- docs/command-reference.md
Elaborated on use of help command to help users make effective use of it, as per https://jira.wandisco.com/browse/DOCU-907
> Improvement ticket - help command elaboration

- docs/command-reference.md
As per https://jira.wandisco.com/browse/DOCU-1028
> Added --user parameter to connect hivemigrator/livemigrator

- docs/uc-on-prem-hadoop-aws-s3-glue.md
For https://jira.wandisco.com/browse/DOCU-1099
Due to the ease of testing (and the fact LDM automatically sanity tests its filesystems and hive agents), the section wound up sparser than the DOCU ticket initially suggested.
> Finished work on requirement DAS-004

- docs/configure-storage.md
Some minor tweaks to the configure storage page, as numerous field names were inaccurate to what's actually displayed in OneUI.
> Updated UI fields

- docs/command-reference.md
As per https://jira.wandisco.com/browse/DOCU-1047
> livedata-migration --version command

- docs/backup-and-restore.md
- docs/command-reference.md
- docs/configuration-ldm.md
- docs/configuration-ui.md
- docs/configure-smtp.md
- sidebars.js
Based on https://jira.wandisco.com/browse/DOCU-1088 and https://jira.wandisco.com/browse/DOCU-1089
I had no clue where to put this stuff honestly, and thought about it for a very long time. I think it's best as its own page, but notifications will require its own page too.
The "email notifications" links are just placeholders, and will be updated when I document that next.
> DOCU-1089 and 1088

- docs/configure-storage.md
- docs/troubleshooting.md
https://jira.wandisco.com/browse/DOCU-1124
> Added vague admonition and troubleshooting, best possible right now

- docs/network.md
Corrections to LDM ports made through slack discussion. (See DOCU-1148).
> DOCU-1148 port corrections for LDM-HVM

- docs/command-reference.md
- docs/connect-metastores.md
https://jira.wandisco.com/browse/DOCU-1156
> Added Ben's suggested content

- docs/configuration-ui.md
https://jira.wandisco.com/browse/DOCU-1169
> LDAP User Authentication & Privilege Assignment

- docs/configuration-ui.md
As per https://jira.wandisco.com/browse/DOCU-1125
> LDAP admin user password reset instructions

- docs/configure-smtp.md
https://jira.wandisco.com/browse/DOCU-1190
https://jira.wandisco.com/browse/DOCU-1191
https://jira.wandisco.com/browse/DOCU-1194
> Implemented new email notifications, email notification test

- docs/command-reference.md
- docs/preview-features.md
Additionally added new h2 for preview features that do not require enablement.
https://jira.wandisco.com/browse/DOCU-1183
> Documented S3 as a source

- docs/create-path-mappings.md
- docs/manage-migrations.md
RE https://jira.wandisco.com/browse/DOCU-1174
> Documented path mappings in UI, made small corrections elsewhere

- docs/prereqs.md
As per https://jira.wandisco.com/browse/DOCU-1198
> Added Mark's work

- docs/configure-storage.md
As per https://jira.wandisco.com/browse/DOCU-1142 and https://jira.wandisco.com/browse/DOCU-1192
> Success file documentation

- docs/audit-logs.md
https://jira.wandisco.com/browse/DOCU-1187
> Changed log location

- docs/manage-migrations.md
Based on https://jira.wandisco.com/browse/DOCU-1167
> Added migration metrics content

- docs/prereqs.md
As per https://jira.wandisco.com/browse/DOCU-1210
> Appended keytab information for Hive Migration

- docs/backup-and-restore.md
- docs/preview-features.md
As per https://jira.wandisco.com/browse/DOCU-1224
> Simple update to preview features info

- docs/manage-migrations.md
As per https://jira.wandisco.com/browse/DOCU-1227
> Copied warning to manage-migrations page
